from . import estate_property
from . import estate_unit
from . import estate_maintenance
from . import res_partner
from . import estate_lease
from . import estate_rent_schedule
from . import estate_deposit
from . import estate_charge
from . import account_move
from . import res_config_settings
from . import estate_dashboard
